import { $ModelPartAccessor } from "@package/dev/engine_room/flywheel/impl/mixin";
import { $EntityModelLayersAccessor } from "@package/net/fabricmc/fabric/mixin/client/rendering";
import { $ProfilerFiller } from "@package/net/minecraft/util/profiling";
import { $ModelPartInjector } from "@package/dev/tr7zw/skinlayers/accessor";
import { $Executor_, $CompletableFuture } from "@package/java/util/concurrent";
import { $CallbackInfo } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $ResourceManager, $ResourceManagerReloadListener, $PreparableReloadListener$PreparationBarrier_ } from "@package/net/minecraft/server/packs/resources";
import { $OffsetProvider, $Mesh, $OffsetProvider_ } from "@package/dev/tr7zw/skinlayers/api";
import { $IEMFUnmodifiedLayerRootGetter, $IEMFTextureSizeSupplier, $IEMFCuboidDataSupplier } from "@package/traben/entity_model_features/utils";
import { $List, $Map_, $Map, $Set, $Set_, $List_ } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $EMFModel_ID, $IEMFModelNameContainer } from "@package/traben/entity_model_features/models";
import { $IUpperPartHelper } from "@package/dev/kosmx/playerAnim/impl";
import { $WoodType_ } from "@package/net/minecraft/world/level/block/state/properties";
import { $Direction_ } from "@package/net/minecraft/core";
import { $Stream } from "@package/java/util/stream";
import { $CubeDeformation, $LayerDefinition } from "@package/net/minecraft/client/model/geom/builders";
import { $IModelPartExtension } from "@package/net/mehvahdjukaar/moonlight/api/client/model";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $VertexConsumer, $PoseStack, $PoseStack$Pose } from "@package/com/mojang/blaze3d/vertex";
import { $CuboidAccessor } from "@package/traben/entity_model_features/mixin/mixins/accessor";
import { $Boat$Type_ } from "@package/net/minecraft/world/entity/vehicle";
import { $Vector3f } from "@package/org/joml";
export * as builders from "@package/net/minecraft/client/model/geom/builders";

declare module "@package/net/minecraft/client/model/geom" {
    export class $ModelPart$Cube implements $IEMFCuboidDataSupplier, $CuboidAccessor {
        compile(pose: $PoseStack$Pose, buffer: $VertexConsumer, packedLight: number, packedOverlay: number, color: number): void;
        emf$getTextureXY(): number[];
        emf$getSizeAdd(): number[];
        emf$getTextureUV(): number[];
        setMinY(arg0: number): void;
        setMaxX(arg0: number): void;
        setMinZ(arg0: number): void;
        setMaxY(arg0: number): void;
        setMaxZ(arg0: number): void;
        setMinX(arg0: number): void;
        setPolygons(arg0: $ModelPart$Polygon[]): void;
        minY: number;
        polygons: $ModelPart$Polygon[];
        minX: number;
        maxZ: number;
        maxY: number;
        maxX: number;
        minZ: number;
        constructor(texCoordU: number, texCoordV: number, originX: number, originY: number, originZ: number, dimensionX: number, dimensionY: number, dimensionZ: number, gtowX: number, growY: number, growZ: number, mirror: boolean, texScaleU: number, texScaleV: number, visibleFaces: $Set_<$Direction_>);
    }
    export class $ModelPart$Polygon {
        normal: $Vector3f;
        vertices: $ModelPart$Vertex[];
        constructor(vertices: $ModelPart$Vertex[], u1: number, v1: number, u2: number, v2: number, textureWidth: number, textureHeight: number, mirror: boolean, direction: $Direction_);
    }
    export class $PartNames {
        static RIGHT_LID: string;
        static RIGHT_BLUE_FIN: string;
        static LEFT_HIND_LEG_TIP: string;
        static JAW: string;
        static LEFT_BLUE_FIN: string;
        static RIGHT_TENDRIL: string;
        static LEFT_LID: string;
        static ARMS: string;
        static RIGHT_FRONT_LEG_TIP: string;
        static RIGHT_FIN: string;
        static TOP_FIN: string;
        static FEET: string;
        static LEFT_HAND: string;
        static RIGHT_LEG: string;
        static LEFT_FOOT: string;
        static LEFT_LEG: string;
        static LEFT_HIND_LEG: string;
        static LEFT_HORN: string;
        static LEFT_FIN: string;
        static RIGHT_WING: string;
        static RIGHT_HORN: string;
        static LEFT_FRONT_LEG_TIP: string;
        static RIGHT_GILLS: string;
        static LEFT_FRONT_FOOT: string;
        static RIGHT_FOOT: string;
        static LEFT_ARM: string;
        static RIGHT_FRONT_FOOT: string;
        static RIGHT_HAND: string;
        static RIGHT_CHEST: string;
        static WIND_BOTTOM: string;
        static LEFT_MID_LEG: string;
        static CUBE: string;
        static RODS: string;
        static RIGHT_HIND_FOOT: string;
        static TOP_GILLS: string;
        static RIGHT_RIBCAGE: string;
        static BEAK: string;
        static JACKET: string;
        static TONGUE_R1: string;
        static BACK_FIN: string;
        static TAIL_FIN: string;
        static RIGHT_WING_BASE: string;
        static BODY: string;
        static CROAKING_BODY: string;
        static WIND_MID: string;
        static HEAD: string;
        static EYES: string;
        static ROOT: string;
        static MOUTH: string;
        static HAT_RIM: string;
        static WIND_TOP: string;
        static LEFT_FRONT_LEG: string;
        static TONGUE: string;
        static LEFT_WING_TIP: string;
        static RIGHT_EAR: string;
        static LEFT_EAR: string;
        static LEFT_TENDRIL: string;
        static BONE: string;
        static RIGHT_ARM: string;
        static RIGHT_FRONT_LEG: string;
        static RIGHT_MID_LEG: string;
        static LEFT_CHEST: string;
        static LEFT_RIBCAGE: string;
        static BOTTOM_FIN: string;
        static MANE: string;
        static RIGHT_EYE: string;
        static LEFT_WING_BASE: string;
        static LEFT_WING: string;
        static RIGHT_WING_TIP: string;
        static RIGHT_HIND_LEG: string;
        static RIGHT_HIND_LEG_TIP: string;
        static NOSE: string;
        static TAIL: string;
        static WIND_BODY: string;
        static LEFT_HIND_FOOT: string;
        static HAT: string;
        static NECK: string;
        static LEFT_GILLS: string;
        static LEFT_EYE: string;
        static MUSHROOMS: string;
        constructor();
    }
    export class $ModelPart$Vertex {
        remap(u: number, v: number): $ModelPart$Vertex;
        pos: $Vector3f;
        u: number;
        v: number;
        constructor(x: number, y: number, z: number, u: number, v: number);
        constructor(pos: $Vector3f, u: number, v: number);
    }
    export class $ModelPart implements $ModelPartInjector, $IUpperPartHelper, $ModelPartAccessor, $IEMFTextureSizeSupplier, $IEMFModelNameContainer, $IModelPartExtension {
        isEmpty(): boolean;
        compile(pose: $PoseStack$Pose, buffer: $VertexConsumer, packedLight: number, packedOverlay: number, color: number): void;
        visit(poseStack: $PoseStack, visitor: $ModelPart$Visitor_): void;
        getChild(name: string): $ModelPart;
        copyFrom(modelPart: $ModelPart): void;
        setPos(x: number, y: number, z: number): void;
        isVisible(): boolean;
        offsetRotation(offset: $Vector3f): void;
        offsetScale(offset: $Vector3f): void;
        getInjectedMesh(): $Mesh;
        getAllParts(): $Stream<$ModelPart>;
        getOffsetProvider(): $OffsetProvider;
        emf$getTextureSize(): number[];
        emf$setTextureSize(size: number[]): void;
        getInitialPose(): $PartPose;
        setInitialPose(partPose: $PartPose): void;
        getRandomCube(random: $RandomSource): $ModelPart$Cube;
        render(poseStack: $PoseStack, buffer: $VertexConsumer, packedLight: number, packedOverlay: number): void;
        render(poseStack: $PoseStack, buffer: $VertexConsumer, packedLight: number, packedOverlay: number, color: number): void;
        setUpperPart(bl: boolean): void;
        hasChild(name: string): boolean;
        resetPose(): void;
        loadPose(partPose: $PartPose): void;
        storePose(): $PartPose;
        setRotation(x: number, y: number, z: number): void;
        emf$insertKnownMappings(newName: $EMFModel_ID): void;
        offsetPos(offset: $Vector3f): void;
        moonlight$setDimensions(arg0: number, arg1: number): void;
        moonlight$getTextWidth(): number;
        moonlight$getTextHeight(): number;
        prepareTranslateAndRotate(poseStack: $PoseStack): void;
        isUpperPart(): boolean;
        setInjectedMesh(mesh: $Mesh, offsetProvider: $OffsetProvider_): void;
        translateAndRotate(poseStack: $PoseStack): void;
        handler$jch000$skinlayers3d$render(poseStack: $PoseStack, vertexConsumer: $VertexConsumer, light: number, overlay: number, color: number, ci: $CallbackInfo): void;
        handler$dfn000$xaerominimap$onRender(arg0: $PoseStack$Pose, arg1: $VertexConsumer, arg2: number, arg3: number, arg4: number, arg5: $CallbackInfo): void;
        flywheel$compile(pose: $PoseStack$Pose, buffer: $VertexConsumer, packedLight: number, packedOverlay: number, color: number): void;
        flywheel$children(): $Map<string, $ModelPart>;
        visible: boolean;
        static DEFAULT_SCALE: number;
        zRot: number;
        yRot: number;
        xRot: number;
        yScale: number;
        children: $Map<string, $ModelPart>;
        xScale: number;
        cubes: $List<$ModelPart$Cube>;
        initialPose: $PartPose;
        x: number;
        y: number;
        z: number;
        skipDraw: boolean;
        emf$modelInfo: $EMFModel_ID;
        zScale: number;
        constructor(cubes: $List_<$ModelPart$Cube>, children: $Map_<string, $ModelPart>);
        get empty(): boolean;
        get allParts(): $Stream<$ModelPart>;
        get offsetProvider(): $OffsetProvider;
    }
    export class $PartPose {
        static offset(x: number, y: number, z: number): $PartPose;
        static rotation(x: number, y: number, z: number): $PartPose;
        static offsetAndRotation(x: number, y: number, z: number, xRot: number, yRot: number, zRot: number): $PartPose;
        static ZERO: $PartPose;
        zRot: number;
        yRot: number;
        x: number;
        xRot: number;
        y: number;
        z: number;
        constructor(x: number, y: number, z: number, xRot: number, yRot: number, zRot: number);
    }
    export class $ModelLayers implements $EntityModelLayersAccessor {
        static createChestBoatModelName(type: $Boat$Type_): $ModelLayerLocation;
        static createBoatModelName(type: $Boat$Type_): $ModelLayerLocation;
        static createRaftModelName(type: $Boat$Type_): $ModelLayerLocation;
        static createSignModelName(woodType: $WoodType_): $ModelLayerLocation;
        static createChestRaftModelName(type: $Boat$Type_): $ModelLayerLocation;
        static createHangingSignModelName(woodType: $WoodType_): $ModelLayerLocation;
        static getLayers$fabric_rendering_v1_$md$66668e$0(): $Set<any>;
        static getKnownLocations(): $Stream<$ModelLayerLocation>;
        static MOOSHROOM: $ModelLayerLocation;
        static MAGMA_CUBE: $ModelLayerLocation;
        static SILVERFISH: $ModelLayerLocation;
        static MULE: $ModelLayerLocation;
        static HOGLIN: $ModelLayerLocation;
        static LEASH_KNOT: $ModelLayerLocation;
        static PIGLIN_HEAD: $ModelLayerLocation;
        static HUSK: $ModelLayerLocation;
        static VINDICATOR: $ModelLayerLocation;
        static WARDEN: $ModelLayerLocation;
        static BED_FOOT: $ModelLayerLocation;
        static CONDUIT_WIND: $ModelLayerLocation;
        static HOPPER_MINECART: $ModelLayerLocation;
        static SKELETON_SKULL: $ModelLayerLocation;
        static PILLAGER: $ModelLayerLocation;
        static SHULKER_BULLET: $ModelLayerLocation;
        static VILLAGER: $ModelLayerLocation;
        static TURTLE: $ModelLayerLocation;
        static STRAY_INNER_ARMOR: $ModelLayerLocation;
        static TRADER_LLAMA: $ModelLayerLocation;
        static BELL: $ModelLayerLocation;
        static BREEZE_WIND: $ModelLayerLocation;
        static CAVE_SPIDER: $ModelLayerLocation;
        static SLIME: $ModelLayerLocation;
        static DROWNED: $ModelLayerLocation;
        static SKELETON_OUTER_ARMOR: $ModelLayerLocation;
        static EVOKER: $ModelLayerLocation;
        static WITHER_SKELETON_OUTER_ARMOR: $ModelLayerLocation;
        static DECORATED_POT_SIDES: $ModelLayerLocation;
        static PUFFERFISH_MEDIUM: $ModelLayerLocation;
        static ZOMBIE_HEAD: $ModelLayerLocation;
        static ENDERMITE: $ModelLayerLocation;
        static AXOLOTL: $ModelLayerLocation;
        static CHEST: $ModelLayerLocation;
        static COMMAND_BLOCK_MINECART: $ModelLayerLocation;
        static PLAYER: $ModelLayerLocation;
        static DOUBLE_CHEST_RIGHT: $ModelLayerLocation;
        static SALMON: $ModelLayerLocation;
        static ZOMBIE: $ModelLayerLocation;
        static GIANT_OUTER_ARMOR: $ModelLayerLocation;
        static PLAYER_HEAD: $ModelLayerLocation;
        static GOAT: $ModelLayerLocation;
        static STRIDER: $ModelLayerLocation;
        static PANDA: $ModelLayerLocation;
        static PIGLIN_BRUTE_INNER_ARMOR: $ModelLayerLocation;
        static OCELOT: $ModelLayerLocation;
        static DROWNED_INNER_ARMOR: $ModelLayerLocation;
        static BOGGED_OUTER_ARMOR: $ModelLayerLocation;
        static ENDERMAN: $ModelLayerLocation;
        static CHEST_MINECART: $ModelLayerLocation;
        static ZOMBIE_VILLAGER: $ModelLayerLocation;
        static LLAMA: $ModelLayerLocation;
        static ENDER_DRAGON: $ModelLayerLocation;
        static WOLF_ARMOR: $ModelLayerLocation;
        static WITCH: $ModelLayerLocation;
        static ARMADILLO: $ModelLayerLocation;
        static STRAY_OUTER_LAYER: $ModelLayerLocation;
        static WITHER: $ModelLayerLocation;
        static WITHER_SKELETON_SKULL: $ModelLayerLocation;
        static ZOMBIFIED_PIGLIN_OUTER_ARMOR: $ModelLayerLocation;
        static CREEPER: $ModelLayerLocation;
        static BOGGED: $ModelLayerLocation;
        static ILLUSIONER: $ModelLayerLocation;
        static BREEZE: $ModelLayerLocation;
        static CAMEL: $ModelLayerLocation;
        static ZOMBIE_VILLAGER_OUTER_ARMOR: $ModelLayerLocation;
        static COD: $ModelLayerLocation;
        static PIGLIN_OUTER_ARMOR: $ModelLayerLocation;
        static ZOMBIE_HORSE: $ModelLayerLocation;
        static FURNACE_MINECART: $ModelLayerLocation;
        static RAVAGER: $ModelLayerLocation;
        static DROWNED_OUTER_LAYER: $ModelLayerLocation;
        static SHULKER: $ModelLayerLocation;
        static SNIFFER: $ModelLayerLocation;
        static BEE: $ModelLayerLocation;
        static TROPICAL_FISH_LARGE_PATTERN: $ModelLayerLocation;
        static ZOMBIE_INNER_ARMOR: $ModelLayerLocation;
        static PHANTOM: $ModelLayerLocation;
        static BLAZE: $ModelLayerLocation;
        static PLAYER_SLIM_OUTER_ARMOR: $ModelLayerLocation;
        static SKELETON_HORSE: $ModelLayerLocation;
        static COW: $ModelLayerLocation;
        static HUSK_INNER_ARMOR: $ModelLayerLocation;
        static WANDERING_TRADER: $ModelLayerLocation;
        static ARMOR_STAND_INNER_ARMOR: $ModelLayerLocation;
        static END_CRYSTAL: $ModelLayerLocation;
        static PIG: $ModelLayerLocation;
        static PLAYER_OUTER_ARMOR: $ModelLayerLocation;
        static ZOGLIN: $ModelLayerLocation;
        static STRIDER_SADDLE: $ModelLayerLocation;
        static BANNER: $ModelLayerLocation;
        static TROPICAL_FISH_SMALL: $ModelLayerLocation;
        static WOLF: $ModelLayerLocation;
        static CAT_COLLAR: $ModelLayerLocation;
        static IRON_GOLEM: $ModelLayerLocation;
        static BED_HEAD: $ModelLayerLocation;
        static CREEPER_HEAD: $ModelLayerLocation;
        static FROG: $ModelLayerLocation;
        static DOUBLE_CHEST_LEFT: $ModelLayerLocation;
        static PIG_SADDLE: $ModelLayerLocation;
        static SHEEP: $ModelLayerLocation;
        static VEX: $ModelLayerLocation;
        static PUFFERFISH_SMALL: $ModelLayerLocation;
        static TROPICAL_FISH_LARGE: $ModelLayerLocation;
        static WITHER_SKELETON_INNER_ARMOR: $ModelLayerLocation;
        static TRIDENT: $ModelLayerLocation;
        static PIGLIN_BRUTE: $ModelLayerLocation;
        static PLAYER_SLIM: $ModelLayerLocation;
        static SKELETON_INNER_ARMOR: $ModelLayerLocation;
        static POLAR_BEAR: $ModelLayerLocation;
        static DRAGON_SKULL: $ModelLayerLocation;
        static MINECART: $ModelLayerLocation;
        static GIANT_INNER_ARMOR: $ModelLayerLocation;
        static CREEPER_ARMOR: $ModelLayerLocation;
        static SQUID: $ModelLayerLocation;
        static ELDER_GUARDIAN: $ModelLayerLocation;
        static ELYTRA: $ModelLayerLocation;
        static HORSE: $ModelLayerLocation;
        static LLAMA_DECOR: $ModelLayerLocation;
        static TNT_MINECART: $ModelLayerLocation;
        static TROPICAL_FISH_SMALL_PATTERN: $ModelLayerLocation;
        static ARMOR_STAND: $ModelLayerLocation;
        static DECORATED_POT_BASE: $ModelLayerLocation;
        static PARROT: $ModelLayerLocation;
        static ARMOR_STAND_OUTER_ARMOR: $ModelLayerLocation;
        static EVOKER_FANGS: $ModelLayerLocation;
        static FOX: $ModelLayerLocation;
        static GIANT: $ModelLayerLocation;
        static STRAY: $ModelLayerLocation;
        static DROWNED_OUTER_ARMOR: $ModelLayerLocation;
        static PIGLIN_INNER_ARMOR: $ModelLayerLocation;
        static CAT: $ModelLayerLocation;
        static STRAY_OUTER_ARMOR: $ModelLayerLocation;
        static RABBIT: $ModelLayerLocation;
        static DONKEY: $ModelLayerLocation;
        static SHEEP_FUR: $ModelLayerLocation;
        static ZOMBIE_VILLAGER_INNER_ARMOR: $ModelLayerLocation;
        static SPAWNER_MINECART: $ModelLayerLocation;
        static PLAYER_INNER_ARMOR: $ModelLayerLocation;
        static PLAYER_SLIM_INNER_ARMOR: $ModelLayerLocation;
        static BOGGED_OUTER_LAYER: $ModelLayerLocation;
        static CONDUIT_CAGE: $ModelLayerLocation;
        static PUFFERFISH_BIG: $ModelLayerLocation;
        static CONDUIT_EYE: $ModelLayerLocation;
        static ALLAY: $ModelLayerLocation;
        static SPIDER: $ModelLayerLocation;
        static SKELETON: $ModelLayerLocation;
        static WITHER_SKELETON: $ModelLayerLocation;
        static PIGLIN_BRUTE_OUTER_ARMOR: $ModelLayerLocation;
        static SHIELD: $ModelLayerLocation;
        static HORSE_ARMOR: $ModelLayerLocation;
        static CHICKEN: $ModelLayerLocation;
        static ZOMBIFIED_PIGLIN: $ModelLayerLocation;
        static SLIME_OUTER: $ModelLayerLocation;
        static PLAYER_SPIN_ATTACK: $ModelLayerLocation;
        static GLOW_SQUID: $ModelLayerLocation;
        static SNOW_GOLEM: $ModelLayerLocation;
        static WITHER_SKULL: $ModelLayerLocation;
        static GUARDIAN: $ModelLayerLocation;
        static LLAMA_SPIT: $ModelLayerLocation;
        static WIND_CHARGE: $ModelLayerLocation;
        static WITHER_ARMOR: $ModelLayerLocation;
        static HUSK_OUTER_ARMOR: $ModelLayerLocation;
        static PIGLIN: $ModelLayerLocation;
        static GHAST: $ModelLayerLocation;
        static ZOMBIFIED_PIGLIN_INNER_ARMOR: $ModelLayerLocation;
        static ZOMBIE_OUTER_ARMOR: $ModelLayerLocation;
        static BOGGED_INNER_ARMOR: $ModelLayerLocation;
        static BAT: $ModelLayerLocation;
        static DOLPHIN: $ModelLayerLocation;
        static TADPOLE: $ModelLayerLocation;
        static ALL_MODELS: $Set<$ModelLayerLocation>;
        static BOOK: $ModelLayerLocation;
        static CONDUIT_SHELL: $ModelLayerLocation;
        constructor();
        static get layers$fabric_rendering_v1_$md$66668e$0(): $Set<any>;
        static get knownLocations(): $Stream<$ModelLayerLocation>;
    }
    export class $EntityModelSet implements $ResourceManagerReloadListener, $IEMFUnmodifiedLayerRootGetter {
        onResourceManagerReload(resourceManager: $ResourceManager): void;
        bakeLayer(modelLayerLocation: $ModelLayerLocation): $ModelPart;
        emf$getUnmodifiedRoots(): $Map<any, any>;
        reload(preparationBarrier: $PreparableReloadListener$PreparationBarrier_, resourceManager: $ResourceManager, preparationsProfiler: $ProfilerFiller, reloadProfiler: $ProfilerFiller, backgroundExecutor: $Executor_, gameExecutor: $Executor_): $CompletableFuture<void>;
        getName(): string;
        roots: $Map<$ModelLayerLocation, $LayerDefinition>;
        constructor();
        get name(): string;
    }
    export class $ModelPart$Visitor {
    }
    export interface $ModelPart$Visitor {
        visit(pose: $PoseStack$Pose, path: string, index: number, cube: $ModelPart$Cube): void;
    }
    /**
     * Values that may be interpreted as {@link $ModelPart$Visitor}.
     */
    export type $ModelPart$Visitor_ = ((arg0: $PoseStack$Pose, arg1: string, arg2: number, arg3: $ModelPart$Cube) => void);
    export class $ModelLayerLocation {
        getLayer(): string;
        getModel(): $ResourceLocation;
        constructor(model: $ResourceLocation_, layer: string);
        get layer(): string;
        get model(): $ResourceLocation;
    }
    export class $LayerDefinitions {
        static createRoots(): $Map<$ModelLayerLocation, $LayerDefinition>;
        static INNER_ARMOR_DEFORMATION: $CubeDeformation;
        static OUTER_ARMOR_DEFORMATION: $CubeDeformation;
        constructor();
    }
}
