StartupEvents.registry('block', event => {
    event.create('kevdelights:jar_of_chocolate', 'cardinal') 
        .displayName('Jar of Chocolate')
        .soundType('decorated_pot')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(4, 0, 4, 12, 13, 12)
    
    event.create('kevdelights:jar_of_jam', 'cardinal') 
        .displayName('Jar of Jam')
        .soundType('decorated_pot')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(4, 0, 4, 12, 13, 12)
})