declare module "com.furiusmax.bjornlib.ability.Ability" {
import {$Player, $Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$CompoundTag$$Type} from "net.minecraft.nbt.CompoundTag"
import {$AbilityType, $AbilityType$$Type} from "com.furiusmax.bjornlib.ability.AbilityType"
import {$IPlayerAbilities$$Type} from "com.furiusmax.bjornlib.capability.IPlayerAbilities"

export class $Ability {
 "maxLevel": integer
 "cost": float
 "level": integer
 "cooldown": float
 "cooldownTimer": float
readonly "type": $AbilityType

constructor(arg0: $AbilityType$$Type, arg1: $Player$$Type, arg2: integer)

public "tick"(): void
public "getLevel"(): integer
public "setLevel"(arg0: integer): $Ability
public "readTag"(arg0: $CompoundTag$$Type): void
public "writeTag"(arg0: $CompoundTag$$Type): void
public "getMaxLevel"(): integer
public "getCost"(): float
public "getPlayer"(): $Player
public "setPlayer"(arg0: $Player$$Type): void
public "levelUp"(arg0: $IPlayerAbilities$$Type, arg1: boolean): void
public "canCastAbility"(): boolean
get "player"(): $Player
set "player"(value: $Player$$Type)
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Ability$$Type = ($Ability);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Ability$$Original = $Ability;}
declare module "com.furiusmax.bjornlib.ability.AbilityType" {
import {$Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$Ability, $Ability$$Type} from "com.furiusmax.bjornlib.ability.Ability"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$IPlayerAbilities$$Type} from "com.furiusmax.bjornlib.capability.IPlayerAbilities"
import {$AbilityType$AbilityCastType, $AbilityType$AbilityCastType$$Type} from "com.furiusmax.bjornlib.ability.AbilityType$AbilityCastType"
import {$Component} from "net.minecraft.network.chat.Component"

export class $AbilityType {
static readonly "EMPTY": $AbilityType

constructor(arg0: $ResourceLocation$$Type, arg1: integer, arg2: float, arg3: $AbilityType$AbilityCastType$$Type, arg4: $AbilityType$$Type)
constructor(arg0: $ResourceLocation$$Type, arg1: integer, arg2: float, arg3: $AbilityType$AbilityCastType$$Type)

public "getDescription"(arg0: integer): $Component
public "getName"(): $Component
public "getParent"(): $AbilityType
public "getId"(): $ResourceLocation
public "getMaxLevel"(): integer
public "getCost"(): float
public "getCastType"(): $AbilityType$AbilityCastType
public "createAbility"(arg0: $Player$$Type, arg1: integer): $Ability
public "onLevelUp"(arg0: $IPlayerAbilities$$Type, arg1: $Ability$$Type): boolean
get "name"(): $Component
get "parent"(): $AbilityType
get "id"(): $ResourceLocation
get "maxLevel"(): integer
get "cost"(): float
get "castType"(): $AbilityType$AbilityCastType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.BjornlibBjornAbility
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.BjornlibBjornAbilityTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AbilityType$$Type = (Special.BjornlibBjornAbility);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AbilityType$$Original = $AbilityType;}
declare module "com.furiusmax.bjornlib.ability.AbilityType$AbilityCastType" {
import {$Enum} from "java.lang.Enum"

export class $AbilityType$AbilityCastType extends $Enum<($AbilityType$AbilityCastType)> {
static readonly "PASSIVE": $AbilityType$AbilityCastType
static readonly "VIEWING": $AbilityType$AbilityCastType
static readonly "ENTITY_TARGET": $AbilityType$AbilityCastType
static readonly "SELF": $AbilityType$AbilityCastType
static readonly "BLOCK_TARGET": $AbilityType$AbilityCastType

public static "values"(): ($AbilityType$AbilityCastType)[]
public static "valueOf"(arg0: StringJS): $AbilityType$AbilityCastType
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AbilityType$AbilityCastType$$Type = (("passive") | ("self") | ("viewing") | ("block_target") | ("entity_target"));
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AbilityType$AbilityCastType$$Original = $AbilityType$AbilityCastType;}
