declare module "com.lightning.northstar.contraption.FuelType$Builder" {
import {$Mod$$Type} from "com.lightning.northstar.data.Mod"
import {$Fluid$$Type} from "net.minecraft.world.level.material.Fluid"
import {$ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$TagKey$$Type} from "net.minecraft.tags.TagKey"
import {$Tags$Tag$$Type} from "com.lightning.northstar.data.Tags$Tag"
import {$FluidEntry$$Type} from "com.tterrag.registrate.util.entry.FluidEntry"
import {$FuelType} from "com.lightning.northstar.contraption.FuelType"

export class $FuelType$Builder {
constructor()

public "build"(): $FuelType
public "tag"(tag: $Tags$Tag$$Type<($Fluid$$Type)>): $FuelType$Builder
public "tag"(tag: $ResourceLocation$$Type): $FuelType$Builder
public "tag"(mod: $Mod$$Type, tag: StringJS): $FuelType$Builder
public "tag"(tag: $TagKey$$Type<($Fluid)>): $FuelType$Builder
public "fluid"(mod: $Mod$$Type, tag: StringJS): $FuelType$Builder
public "fluid"(fluid: $Fluid$$Type): $FuelType$Builder
public "fluid"(fluid: $FluidEntry$$Type<(never)>): $FuelType$Builder
public "gjPerMb"(gjPerMb: float): $FuelType$Builder
public "combustionEngine"(usePerTick: float, rpm: float): $FuelType$Builder
public "rawFluid"(fluid: $ResourceLocation$$Type): $FuelType$Builder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FuelType$Builder$$Type = ($FuelType$Builder);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FuelType$Builder$$Original = $FuelType$Builder;}
declare module "com.lightning.northstar.contraption.FuelType" {
import {$FuelType$Builder} from "com.lightning.northstar.contraption.FuelType$Builder"
import {$Fluid$$Type} from "net.minecraft.world.level.material.Fluid"
import {$Codec} from "com.mojang.serialization.Codec"
import {$List, $List$$Type} from "java.util.List"
import {$RegistryAccess$$Type} from "net.minecraft.core.RegistryAccess"
import {$Record} from "java.lang.Record"

export class $FuelType extends $Record {
static readonly "CODEC": $Codec<($FuelType)>

constructor(fluids: $List$$Type<(StringJS)>, gjPerMb: float, combustionEngineUse: float, combustionEngineRpm: float)

public "equals"(o: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public static "builder"(): $FuelType$Builder
public static "recacheFuels"(registryAccess: $RegistryAccess$$Type): void
public "combustionEngineUse"(): float
public "combustionEngineRpm"(): float
public "fluids"(): $List<(StringJS)>
public "supports"(fluid: $Fluid$$Type): boolean
public static "getFuelType"(fluid: $Fluid$$Type): $FuelType
public "gjPerMb"(): float
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.NorthstarFuelType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.NorthstarFuelTypeTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FuelType$$Type = (Special.NorthstarFuelType) | ({"combustionEngineUse"?: float, "combustionEngineRpm"?: float, "fluids"?: $List$$Type<(StringJS)>, "gjPerMb"?: float}) | ([combustionEngineUse?: float, combustionEngineRpm?: float, fluids?: $List$$Type<(StringJS)>, gjPerMb?: float]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FuelType$$Original = $FuelType;}
