declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Blasting" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Blasting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Blasting$$Type = ($Blasting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Blasting$$Original = $Blasting;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Stonecutting" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Stonecutting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Stonecutting$$Type = ($Stonecutting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Stonecutting$$Original = $Stonecutting;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.VillagerType" {
import {$VillagerTypeBuilder} from "dev.latvian.mods.kubejs.misc.VillagerTypeBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$VillagerType as $VillagerType$0} from "net.minecraft.world.entity.npc.VillagerType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VillagerType extends $RegistryKubeEvent<($VillagerType$0)> {
public "create"(name: StringJS): $VillagerTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VillagerType$$Type = ($VillagerType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VillagerType$$Original = $VillagerType;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Attribute" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Attribute as $Attribute$0} from "net.minecraft.world.entity.ai.attributes.Attribute"
import {$AttributeBuilder} from "dev.latvian.mods.kubejs.entity.AttributeBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Attribute extends $RegistryKubeEvent<($Attribute$0)> {
public "create"(name: StringJS): $AttributeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Attribute$$Type = ($Attribute);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Attribute$$Original = $Attribute;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShapeless" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CraftingShapeless extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "category"(category: $CraftingBookCategory$$Type): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CraftingShapeless$$Type = ($CraftingShapeless);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CraftingShapeless$$Original = $CraftingShapeless;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.CreativeModeTab" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$CreativeModeTab as $CreativeModeTab$0} from "net.minecraft.world.item.CreativeModeTab"
import {$CreativeTabBuilder} from "dev.latvian.mods.kubejs.item.creativetab.CreativeTabBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CreativeModeTab extends $RegistryKubeEvent<($CreativeModeTab$0)> {
public "create"(name: StringJS): $CreativeTabBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CreativeModeTab$$Type = ($CreativeModeTab);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CreativeModeTab$$Original = $CreativeModeTab;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTrim" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SmithingTrim extends $KubeRecipe {
public "template"(template: $Ingredient$$Type): this
public "base"(base: $Ingredient$$Type): this
public "addition"(addition: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SmithingTrim$$Type = ($SmithingTrim);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SmithingTrim$$Original = $SmithingTrim;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.ArmorMaterial" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ArmorMaterial as $ArmorMaterial$0} from "net.minecraft.world.item.ArmorMaterial"
import {$ArmorMaterialBuilder} from "dev.latvian.mods.kubejs.item.ArmorMaterialBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ArmorMaterial extends $RegistryKubeEvent<($ArmorMaterial$0)> {
public "create"(name: StringJS): $ArmorMaterialBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ArmorMaterial$$Type = ($ArmorMaterial);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ArmorMaterial$$Original = $ArmorMaterial;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShaped" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CraftingShaped extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "pattern"(pattern: $List$$Type<(StringJS)>): this
public "key"(key: $Map$$Type<(character), ($Ingredient$$Type)>): this
public "kjsMirror"(kjsMirror: boolean): this
public "kjsShrink"(kjsShrink: boolean): this
public "category"(category: $CraftingBookCategory$$Type): this
public "showNotification"(showNotification: boolean): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
public "noShrink"(): this
public "noNotification"(): this
public "noMirror"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CraftingShaped$$Type = ($CraftingShaped);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CraftingShaped$$Original = $CraftingShaped;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.CustomStat" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"
import {$CustomStatBuilder} from "dev.latvian.mods.kubejs.misc.CustomStatBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CustomStat extends $RegistryKubeEvent<($ResourceLocation)> {
public "create"(name: StringJS): $CustomStatBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomStat$$Type = ($CustomStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomStat$$Original = $CustomStat;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CampfireCooking" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CampfireCooking extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CampfireCooking$$Type = ($CampfireCooking);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CampfireCooking$$Original = $CampfireCooking;}
declare module "moe.wolfgirl.probejs.generated.registry.neoforge.FluidType" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$FluidTypeBuilder} from "dev.latvian.mods.kubejs.fluid.FluidTypeBuilder"
import {$FluidType as $FluidType$0} from "net.neoforged.neoforge.fluids.FluidType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $FluidType extends $RegistryKubeEvent<($FluidType$0)> {
public "create"(name: StringJS): $FluidTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FluidType$$Type = ($FluidType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FluidType$$Original = $FluidType;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Block" {
import {$CarpetBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CarpetBlockBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$SlabBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.SlabBlockBuilder"
import {$DoorBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.DoorBlockBuilder"
import {$StairBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.StairBlockBuilder"
import {$Block as $Block$0} from "net.minecraft.world.level.block.Block"
import {$PressurePlateBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.PressurePlateBlockBuilder"
import {$BasicKubeBlock$Builder} from "dev.latvian.mods.kubejs.block.custom.BasicKubeBlock$Builder"
import {$CropBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CropBlockBuilder"
import {$ButtonBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.ButtonBlockBuilder"
import {$FenceBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FenceBlockBuilder"
import {$TrapdoorBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.TrapdoorBlockBuilder"
import {$WallBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.WallBlockBuilder"
import {$CardinalBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CardinalBlockBuilder"
import {$FenceGateBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FenceGateBlockBuilder"
import {$FallingBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FallingBlockBuilder"
import {$DetectorBlock$Builder} from "dev.latvian.mods.kubejs.block.DetectorBlock$Builder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Block extends $RegistryKubeEvent<($Block$0)> {
public "create"(name: StringJS): $BasicKubeBlock$Builder
public "create"(name: StringJS, type: "kubejs:detector"): $DetectorBlock$Builder
public "create"(name: StringJS, type: "kubejs:slab"): $SlabBlockBuilder
public "create"(name: StringJS, type: "kubejs:stairs"): $StairBlockBuilder
public "create"(name: StringJS, type: "kubejs:fence"): $FenceBlockBuilder
public "create"(name: StringJS, type: "kubejs:wall"): $WallBlockBuilder
public "create"(name: StringJS, type: "kubejs:fence_gate"): $FenceGateBlockBuilder
public "create"(name: StringJS, type: "kubejs:pressure_plate"): $PressurePlateBlockBuilder
public "create"(name: StringJS, type: "kubejs:button"): $ButtonBlockBuilder
public "create"(name: StringJS, type: "kubejs:falling"): $FallingBlockBuilder
public "create"(name: StringJS, type: "kubejs:crop"): $CropBlockBuilder
public "create"(name: StringJS, type: "kubejs:cardinal"): $CardinalBlockBuilder
public "create"(name: StringJS, type: "kubejs:carpet"): $CarpetBlockBuilder
public "create"(name: StringJS, type: "kubejs:door"): $DoorBlockBuilder
public "create"(name: StringJS, type: "kubejs:trapdoor"): $TrapdoorBlockBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Block$$Type = ($Block);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Block$$Original = $Block;}
declare module "moe.wolfgirl.probejs.generated.schema.kubejs.Shaped" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Shaped extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "pattern"(pattern: $List$$Type<(StringJS)>): this
public "key"(key: $Map$$Type<(character), ($Ingredient$$Type)>): this
public "kjsMirror"(kjsMirror: boolean): this
public "kjsShrink"(kjsShrink: boolean): this
public "category"(category: $CraftingBookCategory$$Type): this
public "showNotification"(showNotification: boolean): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
public "noShrink"(): this
public "noNotification"(): this
public "noMirror"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Shaped$$Type = ($Shaped);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Shaped$$Original = $Shaped;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Potion" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Potion as $Potion$0} from "net.minecraft.world.item.alchemy.Potion"
import {$PotionBuilder} from "dev.latvian.mods.kubejs.misc.PotionBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Potion extends $RegistryKubeEvent<($Potion$0)> {
public "create"(name: StringJS): $PotionBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Potion$$Type = ($Potion);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Potion$$Original = $Potion;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.SoundEvent" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$SoundEventBuilder} from "dev.latvian.mods.kubejs.misc.SoundEventBuilder"
import {$SoundEvent as $SoundEvent$0} from "net.minecraft.sounds.SoundEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SoundEvent extends $RegistryKubeEvent<($SoundEvent$0)> {
public "create"(name: StringJS): $SoundEventBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoundEvent$$Type = ($SoundEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoundEvent$$Original = $SoundEvent;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Fluid" {
import {$ThickFluidBuilder} from "dev.latvian.mods.kubejs.fluid.ThickFluidBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Fluid as $Fluid$0} from "net.minecraft.world.level.material.Fluid"
import {$ThinFluidBuilder} from "dev.latvian.mods.kubejs.fluid.ThinFluidBuilder"
import {$FluidBuilder} from "dev.latvian.mods.kubejs.fluid.FluidBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Fluid extends $RegistryKubeEvent<($Fluid$0)> {
public "create"(name: StringJS): $FluidBuilder
public "create"(name: StringJS, type: "kubejs:thin"): $ThinFluidBuilder
public "create"(name: StringJS, type: "kubejs:thick"): $ThickFluidBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Fluid$$Type = ($Fluid);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Fluid$$Original = $Fluid;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.VillagerProfession" {
import {$VillagerProfessionBuilder} from "dev.latvian.mods.kubejs.misc.VillagerProfessionBuilder"
import {$VillagerProfession as $VillagerProfession$0} from "net.minecraft.world.entity.npc.VillagerProfession"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VillagerProfession extends $RegistryKubeEvent<($VillagerProfession$0)> {
public "create"(name: StringJS): $VillagerProfessionBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VillagerProfession$$Type = ($VillagerProfession);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VillagerProfession$$Original = $VillagerProfession;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Smelting" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Smelting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Smelting$$Type = ($Smelting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Smelting$$Original = $Smelting;}
declare module "moe.wolfgirl.probejs.generated.schema.kubejs.Shapeless" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Shapeless extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "category"(category: $CraftingBookCategory$$Type): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Shapeless$$Type = ($Shapeless);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Shapeless$$Original = $Shapeless;}
declare module "moe.wolfgirl.probejs.generated.DocumentedRecipes" {
import {$CraftingShaped} from "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShaped"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$Shaped} from "moe.wolfgirl.probejs.generated.schema.kubejs.Shaped"
import {$List$$Type} from "java.util.List"
import {$Smelting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Smelting"
import {$Blasting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Blasting"
import {$CampfireCooking} from "moe.wolfgirl.probejs.generated.schema.minecraft.CampfireCooking"
import {$Stonecutting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Stonecutting"
import {$Shapeless} from "moe.wolfgirl.probejs.generated.schema.kubejs.Shapeless"
import {$Smoking} from "moe.wolfgirl.probejs.generated.schema.minecraft.Smoking"
import {$SmithingTrim} from "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTrim"
import {$CraftingShapeless} from "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShapeless"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"
import {$SmithingTransform} from "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTransform"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $DocumentedRecipes {
 "farmersdelight": {}
 "minecraft": {"stonecutting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type) => $Stonecutting, "smithing_transform": (result: $ItemStack$$Type, template: $Ingredient$$Type, base: $Ingredient$$Type, addition: $Ingredient$$Type) => $SmithingTransform, "crafting_shaped": (result: $ItemStack$$Type, pattern: $List$$Type<(StringJS)>, key: $Map$$Type<(character), ($Ingredient$$Type)>) => $CraftingShaped, "smoking": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Smoking, "smelting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Smelting, "campfire_cooking": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $CampfireCooking, "crafting_shapeless": (result: $ItemStack$$Type, ingredients: $List$$Type<($Ingredient$$Type)>) => $CraftingShapeless, "blasting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Blasting, "smithing_trim": (template: $Ingredient$$Type, base: $Ingredient$$Type, addition: $Ingredient$$Type) => $SmithingTrim}
 "kubejs": {"shaped": (result: $ItemStack$$Type, pattern: $List$$Type<(StringJS)>, key: $Map$$Type<(character), ($Ingredient$$Type)>) => $Shaped, "shapeless": (result: $ItemStack$$Type, ingredients: $List$$Type<($Ingredient$$Type)>) => $Shapeless}
 "tempad": {}
 "sophisticatedstorage": {}
 "jei": {}
 "silentgear": {}
 "extendedcrafting": {}
 "supermartijn642corelib": {}
 "dndesires": {}
 "garnished": {}
 "sophisticatedcore": {}
 "create_dragons_plus": {}
 "create": {}
 "camera": {}
 "dankstorage": {}
 "storagedrawers": {}
 "northstar": {}
 "sophisticatedbackpacks": {}
 "createdieselgenerators": {}
 "refurbished_furniture": {}
 "aquaculture": {}
 "enderstorage": {}
 "create_enchantment_industry": {}
 "sliceanddice": {}
 "chipped": {}
 "createaddition": {}

}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $DocumentedRecipes$$Type = ($DocumentedRecipes);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $DocumentedRecipes$$Original = $DocumentedRecipes;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Item" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ShearsItemBuilder} from "dev.latvian.mods.kubejs.item.custom.ShearsItemBuilder"
import {$DiggerItemBuilder$Axe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Axe"
import {$DiggerItemBuilder$Shovel} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Shovel"
import {$ArmorItemBuilder$Boots} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Boots"
import {$SmithingTemplateItemBuilder} from "dev.latvian.mods.kubejs.item.custom.SmithingTemplateItemBuilder"
import {$ArmorItemBuilder$Helmet} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Helmet"
import {$ArmorItemBuilder$AnimalArmor} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$AnimalArmor"
import {$ArmorItemBuilder$Chestplate} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Chestplate"
import {$SwordItemBuilder} from "dev.latvian.mods.kubejs.item.custom.SwordItemBuilder"
import {$DiggerItemBuilder$Hoe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Hoe"
import {$DiggerItemBuilder$Pickaxe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Pickaxe"
import {$Item as $Item$0} from "net.minecraft.world.item.Item"
import {$ItemBuilder} from "dev.latvian.mods.kubejs.item.ItemBuilder"
import {$ArmorItemBuilder$Leggings} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Leggings"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Item extends $RegistryKubeEvent<($Item$0)> {
public "create"(name: StringJS): $ItemBuilder
public "create"(name: StringJS, type: "kubejs:sword"): $SwordItemBuilder
public "create"(name: StringJS, type: "kubejs:pickaxe"): $DiggerItemBuilder$Pickaxe
public "create"(name: StringJS, type: "kubejs:axe"): $DiggerItemBuilder$Axe
public "create"(name: StringJS, type: "kubejs:shovel"): $DiggerItemBuilder$Shovel
public "create"(name: StringJS, type: "kubejs:hoe"): $DiggerItemBuilder$Hoe
public "create"(name: StringJS, type: "kubejs:shears"): $ShearsItemBuilder
public "create"(name: StringJS, type: "kubejs:helmet"): $ArmorItemBuilder$Helmet
public "create"(name: StringJS, type: "kubejs:chestplate"): $ArmorItemBuilder$Chestplate
public "create"(name: StringJS, type: "kubejs:leggings"): $ArmorItemBuilder$Leggings
public "create"(name: StringJS, type: "kubejs:boots"): $ArmorItemBuilder$Boots
public "create"(name: StringJS, type: "kubejs:animal_armor"): $ArmorItemBuilder$AnimalArmor
public "create"(name: StringJS, type: "kubejs:smithing_template"): $SmithingTemplateItemBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Item$$Type = ($Item);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Item$$Original = $Item;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Smoking" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Smoking extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Smoking$$Type = ($Smoking);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Smoking$$Original = $Smoking;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.MobEffect" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$MobEffectBuilder} from "dev.latvian.mods.kubejs.misc.MobEffectBuilder"
import {$MobEffect as $MobEffect$0} from "net.minecraft.world.effect.MobEffect"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $MobEffect extends $RegistryKubeEvent<($MobEffect$0)> {
public "create"(name: StringJS): $MobEffectBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MobEffect$$Type = ($MobEffect);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MobEffect$$Original = $MobEffect;}
declare module "moe.wolfgirl.probejs.generated.TagWrapperProbe" {
import {$TagWrapper} from "dev.latvian.mods.kubejs.server.tag.TagWrapper"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $TagWrapperProbe<T, I> extends $TagWrapper {
public "add"(...filters: (I)[]): this
public "remove"(...filters: (I)[]): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TagWrapperProbe$$Type<T, I> = ($TagWrapperProbe<(T), (I)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TagWrapperProbe$$Original<T, I> = $TagWrapperProbe<(T), (I)>;}
declare module "moe.wolfgirl.probejs.generated.TagEventProbe" {
import {$TagWrapperProbe} from "moe.wolfgirl.probejs.generated.TagWrapperProbe"
import {$TagKubeEvent} from "dev.latvian.mods.kubejs.server.tag.TagKubeEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $TagEventProbe<T, I> extends $TagKubeEvent {
public "add"(tag: T, ...filters: (I)[]): $TagWrapperProbe<(T), (I)>
public "remove"(tag: T, ...filters: (I)[]): $TagWrapperProbe<(T), (I)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TagEventProbe$$Type<T, I> = ($TagEventProbe<(T), (I)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TagEventProbe$$Original<T, I> = $TagEventProbe<(T), (I)>;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTransform" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SmithingTransform extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "template"(template: $Ingredient$$Type): this
public "base"(base: $Ingredient$$Type): this
public "addition"(addition: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SmithingTransform$$Type = ($SmithingTransform);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SmithingTransform$$Original = $SmithingTransform;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.ParticleType" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ParticleTypeBuilder} from "dev.latvian.mods.kubejs.misc.ParticleTypeBuilder"
import {$ParticleType as $ParticleType$0} from "net.minecraft.core.particles.ParticleType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ParticleType extends $RegistryKubeEvent<($ParticleType$0)> {
public "create"(name: StringJS): $ParticleTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ParticleType$$Type = ($ParticleType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ParticleType$$Original = $ParticleType;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.PointOfInterestType" {
import {$PoiType} from "net.minecraft.world.entity.ai.village.poi.PoiType"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$PoiTypeBuilder} from "dev.latvian.mods.kubejs.misc.PoiTypeBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $PointOfInterestType extends $RegistryKubeEvent<($PoiType)> {
public "create"(name: StringJS): $PoiTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $PointOfInterestType$$Type = ($PointOfInterestType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $PointOfInterestType$$Original = $PointOfInterestType;}
