declare module "net.minecraft.core.particles.DustParticleOptions" {
import {$ScalableParticleOptionsBase} from "net.minecraft.core.particles.ScalableParticleOptionsBase"
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$ParticleType} from "net.minecraft.core.particles.ParticleType"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$Vector3f, $Vector3f$$Type} from "org.joml.Vector3f"
import {$MapCodec} from "com.mojang.serialization.MapCodec"

export class $DustParticleOptions extends $ScalableParticleOptionsBase {
static readonly "CODEC": $MapCodec<($DustParticleOptions)>
static readonly "MIN_SCALE": float
static readonly "REDSTONE": $DustParticleOptions
static readonly "REDSTONE_PARTICLE_COLOR": $Vector3f
static readonly "MAX_SCALE": float
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($DustParticleOptions)>

constructor(arg0: $Vector3f$$Type, arg1: float)

public "getColor"(): $Vector3f
public "getType"(): $ParticleType<($DustParticleOptions)>
get "color"(): $Vector3f
get "type"(): $ParticleType<($DustParticleOptions)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $DustParticleOptions$$Type = ($DustParticleOptions);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $DustParticleOptions$$Original = $DustParticleOptions;}
declare module "net.minecraft.core.particles.ParticleType" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$ParticleOptions} from "net.minecraft.core.particles.ParticleOptions"

export class $ParticleType<T extends $ParticleOptions> {
public "codec"(): $MapCodec<(T)>
public "streamCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), (T)>
public "getOverrideLimiter"(): boolean
get "overrideLimiter"(): boolean
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.ParticleType
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.ParticleTypeTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ParticleType$$Type<T> = (Special.ParticleType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ParticleType$$Original<T> = $ParticleType<(T)>;}
declare module "net.minecraft.core.particles.SimpleParticleType" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$ParticleType} from "net.minecraft.core.particles.ParticleType"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$MapCodec} from "com.mojang.serialization.MapCodec"
import {$SimpleParticleTypeAccessor$$Interface} from "com.blackgear.platform.core.mixin.access.SimpleParticleTypeAccessor"
import {$ParticleOptions$$Interface} from "net.minecraft.core.particles.ParticleOptions"

export class $SimpleParticleType extends $ParticleType<($SimpleParticleType)> implements $ParticleOptions$$Interface, $SimpleParticleTypeAccessor$$Interface {
constructor(arg0: boolean)

public "getType"(): $ParticleType
public "codec"(): $MapCodec<($SimpleParticleType)>
public "streamCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), ($SimpleParticleType)>
public static "createSimpleParticleType$platform_$md$d44d69$0"(arg0: boolean): $SimpleParticleType
public static "createSimpleParticleType"(overrideLimiter: boolean): $SimpleParticleType
get "type"(): $ParticleType
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SimpleParticleType$$Type = ($SimpleParticleType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SimpleParticleType$$Original = $SimpleParticleType;}
declare module "net.minecraft.core.particles.ParticleOptions" {
import {$ParticleType, $ParticleType$$Type} from "net.minecraft.core.particles.ParticleType"

export interface $ParticleOptions$$Interface {

(): $ParticleType$$Type<(never)>
get "type"(): $ParticleType<(never)>
}

export class $ParticleOptions implements $ParticleOptions$$Interface {
 "getType"(): $ParticleType<(never)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ParticleOptions$$Type = (StringJS) | (() => $ParticleType$$Type<(never)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ParticleOptions$$Original = $ParticleOptions;}
declare module "net.minecraft.core.particles.ScalableParticleOptionsBase" {
import {$ParticleType} from "net.minecraft.core.particles.ParticleType"
import {$ParticleOptions$$Interface} from "net.minecraft.core.particles.ParticleOptions"

export class $ScalableParticleOptionsBase implements $ParticleOptions$$Interface {
static readonly "MIN_SCALE": float
static readonly "MAX_SCALE": float

constructor(arg0: float)

public "getScale"(): float
public "getType"(): $ParticleType<(never)>
get "scale"(): float
get "type"(): $ParticleType<(never)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ScalableParticleOptionsBase$$Type = ($ScalableParticleOptionsBase);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ScalableParticleOptionsBase$$Original = $ScalableParticleOptionsBase;}
declare module "net.minecraft.core.particles.ParticleGroup" {
export {} // Mark the file as a module, do not remove unless there are other import/exports!
export class $ParticleGroup {
static readonly "SPORE_BLOSSOM": $ParticleGroup

constructor(arg0: integer)

public "getLimit"(): integer
get "limit"(): integer
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ParticleGroup$$Type = ($ParticleGroup);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ParticleGroup$$Original = $ParticleGroup;}
