declare module "net.minecraft.sounds.SoundEvent" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$ResourceLocation, $ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$Holder} from "net.minecraft.core.Holder"
import {$ByteBuf} from "io.netty.buffer.ByteBuf"

export class $SoundEvent {
static readonly "CODEC": $Codec<($Holder<($SoundEvent)>)>
static readonly "DIRECT_CODEC": $Codec<($SoundEvent)>
static readonly "DIRECT_STREAM_CODEC": $StreamCodec<($ByteBuf), ($SoundEvent)>
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($Holder<($SoundEvent)>)>

public "getLocation"(): $ResourceLocation
public static "createFixedRangeEvent"(arg0: $ResourceLocation$$Type, arg1: float): $SoundEvent
public static "createVariableRangeEvent"(arg0: $ResourceLocation$$Type): $SoundEvent
public "getRange"(arg0: float): float
get "location"(): $ResourceLocation
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.SoundEvent
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.SoundEventTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoundEvent$$Type = (Special.SoundEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoundEvent$$Original = $SoundEvent;}
declare module "net.minecraft.sounds.Music" {
import {$Codec} from "com.mojang.serialization.Codec"
import {$SoundEvent, $SoundEvent$$Type} from "net.minecraft.sounds.SoundEvent"
import {$Holder, $Holder$$Type} from "net.minecraft.core.Holder"

export class $Music {
static readonly "CODEC": $Codec<($Music)>

constructor(arg0: $Holder$$Type<($SoundEvent)>, arg1: integer, arg2: integer, arg3: boolean)

public "replaceCurrentMusic"(): boolean
public "getEvent"(): $Holder<($SoundEvent)>
public "getMinDelay"(): integer
public "getMaxDelay"(): integer
get "event"(): $Holder<($SoundEvent)>
get "minDelay"(): integer
get "maxDelay"(): integer
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Music$$Type = ($Music);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Music$$Original = $Music;}
declare module "net.minecraft.sounds.SoundSource" {
import {$Enum} from "java.lang.Enum"

export class $SoundSource extends $Enum<($SoundSource)> {
static readonly "RECORDS": $SoundSource
static readonly "MUSIC": $SoundSource
static readonly "MASTER": $SoundSource
static readonly "HOSTILE": $SoundSource
static readonly "PLAYERS": $SoundSource
static readonly "VOICE": $SoundSource
static readonly "WEATHER": $SoundSource
static readonly "BLOCKS": $SoundSource
static readonly "AMBIENT": $SoundSource
static readonly "NEUTRAL": $SoundSource

public "getName"(): StringJS
public static "values"(): ($SoundSource)[]
public static "valueOf"(arg0: StringJS): $SoundSource
get "name"(): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoundSource$$Type = (("master") | ("music") | ("records") | ("weather") | ("blocks") | ("hostile") | ("neutral") | ("players") | ("ambient") | ("voice"));
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoundSource$$Original = $SoundSource;}
