ServerEvents.tags('block', event => {
    const wrenchableBlocks = [
        'minecraft:barrel',
        'minecraft:chest',
        'minecraft:ender_chest',
        'minecraft:trapped_chest',
        'minecraft:dispenser',
        'minecraft:dropper',
        'minecraft:crafter',
        'minecraft:waxed_copper_bulb',
        'minecraft:waxed_exposed_copper_bulb',
        'minecraft:waxed_weathered_copper_bulb',
        'minecraft:waxed_oxidized_copper_bulb',
        'minecraft:copper_bulb',
        'minecraft:exposed_copper_bulb',
        'minecraft:weathered_copper_bulb',
        'minecraft:oxidized_copper_bulb',
        'minecraft:hopper',
        'minecraft:cauldron',
        'minecraft:composter',
        '#c:chains',
        '@dndecor',
        '#create:seats',
        'createdeco:andesite_bars_overlay',
        'createdeco:andesite_bars',
        'createdeco:brass_bars_overlay',
        'createdeco:brass_bars',
        'createdeco:iron_bars_overlay',
        'createdeco:copper_bars_overlay',
        'createdeco:copper_bars',
        'createdeco:industrial_iron_bars_overlay',
        'createdeco:industrial_iron_bars',
        'createdeco:industrial_iron_support',
        'createdeco:zinc_support',
        'createdeco:andesite_sheet_metal',
        'createdeco:brass_sheet_metal',
        'createdeco:iron_sheet_metal',
        'createdeco:copper_sheet_metal',
        'createdeco:industrial_iron_sheet_metal',
        'createdeco:zinc_sheet_metal',
        'createdeco:brass_hull',
        'createdeco:iron_hull',
        'createdeco:copper_hull',
        'createdeco:industrial_iron_hull',
        'createdeco:zinc_hull',
        'createdeco:andesite_support',
        'createdeco:brass_support',
        'createdeco:iron_support',
        'createdeco:copper_support',
        'createdeco:zinc_bars_overlay',
        'createdeco:zinc_bars',
        'createdeco:andesite_mesh_fence',
        'createdeco:brass_mesh_fence',
        'createdeco:iron_mesh_fence',
        'createdeco:copper_mesh_fence',
        'createdeco:industrial_iron_mesh_fence',
        'createdeco:zinc_mesh_fence',
        'createdeco:andesite_hull',
        '#c:glass_blocks'
    ]
    
    event.add('create:wrench_pickup', /.*:.*_trapdoor$/)
    event.add('create:wrench_pickup', wrenchableBlocks);
    
});