import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $MassTracker, $MassData } from "@package/dev/ryanhcode/sable/api/physics/mass";
import { $SubLevelPhysicsSystem } from "@package/dev/ryanhcode/sable/sublevel/system";
import { $BoundingBox3dc, $BoundingBox3i, $Pose3dc, $Pose3d } from "@package/dev/ryanhcode/sable/companion/math";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $GlobalSavedSubLevelPointer, $GlobalSavedSubLevelPointer_ } from "@package/dev/ryanhcode/sable/sublevel/storage/holding";
import { $VeilPacketManager$PacketSink } from "@package/foundry/veil/api/network";
import { $PhysicsPipelineBody } from "@package/dev/ryanhcode/sable/api/physics";
import { $ClientSubLevelAccess, $SubLevelAccess } from "@package/dev/ryanhcode/sable/companion";
import { $RigidBodyHandle } from "@package/dev/ryanhcode/sable/api/physics/handle";
import { $LevelPlot } from "@package/dev/ryanhcode/sable/sublevel/plot";
import { $PrimaryAssemblerExtension } from "@package/dev/simulated_team/simulated/mixin_interface/assembly_preventer";
import { $SubLevelHeatMapManager } from "@package/dev/ryanhcode/sable/sublevel/plot/heat";
import { $ReactionWheelManager } from "@package/dev/ryanhcode/sable/physics";
import { $UUID, $UUID_, $Collection } from "@package/java/util";
import { $ClientLevel } from "@package/net/minecraft/client/multiplayer";
import { $ServerLevel } from "@package/net/minecraft/server/level";
import { $Object2ObjectMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $BlockPos, $BlockPos_ } from "@package/net/minecraft/core";
import { $SubLevelSnapshotInterpolator, $ClientSableInterpolationState } from "@package/dev/ryanhcode/sable/network/client";
import { $FloatingBlockController } from "@package/dev/ryanhcode/sable/physics/floating_block";
import { $QueuedForceGroup, $ForceGroup_, $ForceGroup } from "@package/dev/ryanhcode/sable/api/physics/force";
import { $SubLevelRenderData } from "@package/dev/ryanhcode/sable/sublevel/render";
import { $Vector3d } from "@package/org/joml";
export * as system from "@package/dev/ryanhcode/sable/sublevel/system";
export * as water_occlusion from "@package/dev/ryanhcode/sable/sublevel/water_occlusion";
export * as entity_collision from "@package/dev/ryanhcode/sable/sublevel/entity_collision";
export * as storage from "@package/dev/ryanhcode/sable/sublevel/storage";
export * as plot from "@package/dev/ryanhcode/sable/sublevel/plot";
export * as render from "@package/dev/ryanhcode/sable/sublevel/render";

declare module "@package/dev/ryanhcode/sable/sublevel" {
    export class $ServerSubLevel extends $SubLevel implements $PhysicsPipelineBody, $PrimaryAssemblerExtension {
        getSplitFromSubLevel(): $UUID;
        getReactionWheelManager(): $ReactionWheelManager;
        updateMergedMassData(arg0: number): void;
        setLastNetworkedStopped(arg0: boolean): void;
        lastNetworkedBoundingBox(): $BoundingBox3i;
        prePhysicsTickBegin(): void;
        getFloatingBlockController(): $FloatingBlockController;
        getLastNetworkedStopped(): boolean;
        getQueuedForceGroups(): $Object2ObjectMap<$ForceGroup, $QueuedForceGroup>;
        getSplitFromPose(): $Pose3d;
        clearSplitFrom(): void;
        setSplitFrom(arg0: $ServerSubLevel, arg1: $Pose3d): void;
        getUserDataTag(): $CompoundTag;
        buildMassTracker(): void;
        getHeatMapManager(): $SubLevelHeatMapManager;
        applyQueuedForces(arg0: $SubLevelPhysicsSystem, arg1: $RigidBodyHandle, arg2: number): void;
        getSelfMassTracker(): $MassTracker;
        setUserDataTag(arg0: $CompoundTag_): void;
        lastNetworkedPose(): $Pose3d;
        deleteAllEntities(): void;
        simulated$setPrimaryAssembler(arg0: $BlockPos_): void;
        simulated$getPrimaryAssembler(): $BlockPos;
        setLastSerializationPointer(arg0: $GlobalSavedSubLevelPointer_): void;
        isTrackingIndividualQueuedForces(): boolean;
        getLastSerializationPointer(): $GlobalSavedSubLevelPointer;
        getOrCreateQueuedForceGroup(arg0: $ForceGroup_): $QueuedForceGroup;
        getTrackingPlayers(): $Collection<$UUID>;
        enableIndividualQueuedForcesTracking(arg0: boolean): void;
        playerSink(): $VeilPacketManager$PacketSink;
        getMassTracker(): $MassData;
        getRuntimeId(): number;
        prePhysicsTick(arg0: $SubLevelPhysicsSystem, arg1: $RigidBodyHandle, arg2: number): void;
        latestLinearVelocity: $Vector3d;
        latestAngularVelocity: $Vector3d;
        constructor(arg0: $ServerLevel, arg1: number, arg2: number, arg3: $Pose3d);
        get splitFromSubLevel(): $UUID;
        get reactionWheelManager(): $ReactionWheelManager;
        get floatingBlockController(): $FloatingBlockController;
        get queuedForceGroups(): $Object2ObjectMap<$ForceGroup, $QueuedForceGroup>;
        get splitFromPose(): $Pose3d;
        get heatMapManager(): $SubLevelHeatMapManager;
        get selfMassTracker(): $MassTracker;
        get trackingIndividualQueuedForces(): boolean;
        get trackingPlayers(): $Collection<$UUID>;
        get massTracker(): $MassData;
        get runtimeId(): number;
    }
    export class $SubLevel implements $SubLevelAccess {
        getName(): string;
        setName(arg0: string): void;
        tick(): void;
        getLevel(): $Level;
        getPlot(): $LevelPlot;
        lastPose(): $Pose3dc;
        onRemove(): void;
        getUniqueId(): $UUID;
        isRemoved(): boolean;
        onPlotBoundsChanged(): void;
        forceUpdateGlobalBounds(): void;
        markRemoved(): void;
        setUniqueId(arg0: $UUID_): void;
        updateBoundingBox(): void;
        updateLastPose(): void;
        boundingBox(): $BoundingBox3dc;
        logicalPose(): $Pose3dc;
        get level(): $Level;
        get plot(): $LevelPlot;
        get removed(): boolean;
    }
    export class $ClientSubLevel extends $SubLevel implements $ClientSubLevelAccess {
        getLevel(): $ClientLevel;
        isFinalized(): boolean;
        getRenderData(): $SubLevelRenderData;
        setInitialPosesFrom(arg0: $ClientSableInterpolationState): void;
        getLatestSkyLightScale(): number;
        receiveServerMovementStop(): void;
        computeSubLevelSkyLight(arg0: $Pose3dc): number;
        getLightingSceneId(): number;
        getInterpolator(): $SubLevelSnapshotInterpolator;
        forceUpdateBounds(): void;
        scaleSkyLight(arg0: number): number;
        scaleLightColor(arg0: number): number;
        setFinalized(): void;
        updateRenderData(): void;
        wasSplitFrom(arg0: $ClientSableInterpolationState, arg1: $ClientSubLevel, arg2: $Pose3dc): void;
        setLightingSceneId(arg0: number): void;
        renderPose(arg0: number): $Pose3dc;
        renderPose(): $Pose3dc;
        constructor(arg0: $Level_, arg1: number, arg2: number, arg3: $Pose3d);
        get level(): $ClientLevel;
        get renderData(): $SubLevelRenderData;
        set initialPosesFrom(value: $ClientSableInterpolationState);
        get latestSkyLightScale(): number;
        get interpolator(): $SubLevelSnapshotInterpolator;
    }
}
