StartupEvents.registry('block', event => {
    event.create('justcreatepop:azu_pop', 'cardinal') 
        .displayName('§dAzu Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:beardy_pop', 'cardinal')
        .displayName('§dMrBeardstone Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:block_pop', 'cardinal')
        .displayName('§dBlockdown Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:chosen_pop', 'cardinal')
        .displayName('§dChosenArchitect Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:dave_pop', 'cardinal')
        .displayName('§dImagineerDave Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:deo_pop', 'cardinal')
        .displayName('§dDeosil25 Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)
    
    event.create('justcreatepop:eggs_pop', 'cardinal')
        .displayName('§dEggs98 Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:foxy_pop', 'cardinal')
        .displayName('§dFoxyNoTail Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:frog_pop', 'cardinal')
        .displayName('§dFrogcrafting Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:kev_pop', 'cardinal')
        .displayName('§dArtsByKev Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:rofo_pop', 'cardinal')
        .displayName('§dRofoRex Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:silent_pop', 'cardinal')
        .displayName('§dSilentwisperer Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:stam_pop', 'cardinal')
        .displayName('§dStam1o Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:thro_pop', 'cardinal')
        .displayName('§dThrolash Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

    event.create('justcreatepop:vee_pop', 'cardinal')
        .displayName('§dLegionVee Pop')
        .soundType('candle')
        .hardness(0)
        .defaultCutout()
        .resistance(1.0)
        .requiresTool(false)
        .tag('minecraft:mineable/pickaxe')
        .box(2, 0, 2, 14, 16, 14)

})