import { $PonderTag, $PonderScene } from "@package/net/createmod/ponder/foundation";
import { $NavigatableSimiScreen } from "@package/net/createmod/catnip/gui";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $CubeMap, $PanoramaRenderer } from "@package/net/minecraft/client/renderer";
import { $Executor } from "@package/java/util/concurrent";
import { $NarratableEntry } from "@package/net/minecraft/client/gui/narration";
import { $Component } from "@package/net/minecraft/network/chat";
import { $LerpedFloat } from "@package/net/createmod/catnip/animation";
import { $CycleButton, $WidgetTooltipHolder, $Renderable } from "@package/net/minecraft/client/gui/components";
import { $CallbackInfo } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $Minecraft, $NarratorStatus, $KeyMapping } from "@package/net/minecraft/client";
import { $List, $List_ } from "@package/java/util";
import { $Function } from "@package/java/util/function";
import { $Screen$DeferredTooltipRendering } from "@package/net/minecraft/client/gui/screens";
import { $BoxWidget } from "@package/net/createmod/catnip/gui/widget";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $FadableScreenElement } from "@package/net/createmod/catnip/gui/element";
import { $Pointing_ } from "@package/net/createmod/catnip/math";
import { $Color } from "@package/net/createmod/catnip/theme";
import { $Font, $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $Couple } from "@package/net/createmod/catnip/data";

declare module "@package/net/createmod/ponder/foundation/ui" {
    export class $PonderButton extends $BoxWidget {
        dim(): void;
        getTag(): $PonderTag;
        getItem(): $ItemStack;
        isVisible(): boolean;
        flash(): void;
        showing<T extends $PonderButton>(arg0: $ItemStack_): T;
        withShortcut<T extends $PonderButton>(arg0: $KeyMapping): T;
        showingTag<T extends $PonderButton>(arg0: $PonderTag): T;
        static COLOR_SUCCESS: $Couple<$Color>;
        visible: boolean;
        static HEADER_RGB: $Color;
        lockedTooltipY: number;
        tooltip: $WidgetTooltipHolder;
        static COLOR_HOVER: $Couple<$Color>;
        active: boolean;
        static gradientFactory: $Function<$BoxWidget, $FadableScreenElement>;
        static COLOR_CLICK: $Couple<$Color>;
        packedFGColor: number;
        static UNSET_FG_COLOR: number;
        static HINT_RGB: $Color;
        static COLOR_IDLE: $Couple<$Color>;
        lockedTooltipX: number;
        alpha: number;
        width: number;
        x: number;
        y: number;
        static COLOR_DISABLED: $Couple<$Color>;
        static COLOR_FAIL: $Couple<$Color>;
        height: number;
        constructor(arg0: number, arg1: number);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        get tag(): $PonderTag;
        get item(): $ItemStack;
    }
    export class $PonderUI extends $AbstractPonderScreen {
        static of(arg0: $ResourceLocation_): $PonderUI;
        static of(arg0: $ItemStack_, arg1: $PonderTag): $PonderUI;
        static of(arg0: $ItemStack_): $PonderUI;
        getSubject(): $ItemStack;
        static getPartialTicks(): number;
        getFontRenderer(): $Font;
        seekToTime(arg0: number): void;
        static renderSpeechBox(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: number, arg5: boolean, arg6: $Pointing_, arg7: boolean): void;
        getActiveScene(): $PonderScene;
        coolDownAfterSkip(): void;
        isComfyReadingEnabled(): boolean;
        updateIdentifiedItem(arg0: $PonderScene): void;
        getHoveredTooltipItem(): $ItemStack;
        setComfyReadingEnabled(arg0: boolean): void;
        handler$ink000$petrolpark$inRenderPonderTags(arg0: $PoseStack, arg1: number, arg2: number, arg3: boolean, arg4: $List_<any>, arg5: number, arg6: number, arg7: $GuiGraphics, arg8: number, arg9: number, arg10: $CallbackInfo, arg11: $PonderTag, arg12: $LerpedFloat, arg13: $PonderButton): void;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static IDENTIFY: string;
        static NEXT_UP: string;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        static ponderTicks: number;
        static SLOW_TEXT: string;
        static PONDERING_TAG: string;
        static WELCOME: string;
        static CUBE_MAP: $CubeMap;
        static CLOSE: string;
        title: $Component;
        static COLOR_HIGHLIGHT: $Couple<$Color>;
        static PREVIOUS: string;
        static MISSING_VANILLA_ENTRY: $Couple<$Color>;
        renderables: $List<$Renderable>;
        static INDEX_TITLE: string;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        static DESCRIPTION: string;
        static COLOR_IDLE: $Couple<$Color>;
        static NEXT: string;
        static IDENTIFY_MODE: string;
        static BACKGROUND_IMPORTANT: $Color;
        static PANORAMA: $PanoramaRenderer;
        static ASSOCIATED: string;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        static PONDERING: string;
        static IN_CHAPTER: string;
        static MISSING_MODDED_ENTRY: $Couple<$Color>;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static COLOR_HOVER: $Couple<$Color>;
        static CATEGORIES: string;
        static FOOTER_SEPARATOR: $ResourceLocation;
        transition: $LerpedFloat;
        narratorButton: $CycleButton<$NarratorStatus>;
        static BACKGROUND_TRANSPARENT: $Color;
        static BACKGROUND_FLAT: $Color;
        static REPLAY: string;
        narratables: $List<$NarratableEntry>;
        width: number;
        static ponderPartialTicksPaused: number;
        screenExecutor: $Executor;
        static COLOR_NAV_ARROW: $Couple<$Color>;
        static THINK_BACK: string;
        static EXIT: string;
        font: $Font;
        get subject(): $ItemStack;
        static get partialTicks(): number;
        get fontRenderer(): $Font;
        get activeScene(): $PonderScene;
        get hoveredTooltipItem(): $ItemStack;
    }
    export class $AbstractPonderScreen extends $NavigatableSimiScreen {
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static IDENTIFY: string;
        static NEXT_UP: string;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        static SLOW_TEXT: string;
        static PONDERING_TAG: string;
        static WELCOME: string;
        static CUBE_MAP: $CubeMap;
        static CLOSE: string;
        title: $Component;
        static PREVIOUS: string;
        renderables: $List<$Renderable>;
        static INDEX_TITLE: string;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        static DESCRIPTION: string;
        static NEXT: string;
        static IDENTIFY_MODE: string;
        static PANORAMA: $PanoramaRenderer;
        static ASSOCIATED: string;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        static PONDERING: string;
        static IN_CHAPTER: string;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static CATEGORIES: string;
        static FOOTER_SEPARATOR: $ResourceLocation;
        transition: $LerpedFloat;
        narratorButton: $CycleButton<$NarratorStatus>;
        static REPLAY: string;
        narratables: $List<$NarratableEntry>;
        width: number;
        screenExecutor: $Executor;
        static COLOR_NAV_ARROW: $Couple<$Color>;
        static THINK_BACK: string;
        static EXIT: string;
        font: $Font;
        constructor();
    }
}
