import { $BlockPos, $BlockPos_, $Position } from "@package/net/minecraft/core";
import { $Codec } from "@package/com/mojang/serialization";
import { $Iterable_ } from "@package/java/lang";
import { $BoundingBox } from "@package/net/minecraft/world/level/levelgen/structure";
import { $AABB, $Vec3_, $AABB_, $Vec3 } from "@package/net/minecraft/world/phys";
import { $Matrix4dc, $Vector3dc, $Quaterniond, $Vector3d, $Vector3ic, $Vector3i, $Matrix4d, $Quaterniondc } from "@package/org/joml";

declare module "@package/dev/ryanhcode/sable/companion/math" {
    export class $BoundingBox3d implements $BoundingBox3dc {
        expand(arg0: number): $BoundingBox3d;
        expand(arg0: number, arg1: number, arg2: number): $BoundingBox3d;
        transform(arg0: $Pose3dc, arg1: $Matrix4d): $BoundingBox3d;
        transform(arg0: $Pose3dc): $BoundingBox3d;
        transform(arg0: $Matrix4dc): $BoundingBox3d;
        set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): $BoundingBox3d;
        set(arg0: $BoundingBox3dc): $BoundingBox3d;
        set(arg0: $AABB_): $BoundingBox3d;
        move(arg0: number, arg1: number, arg2: number): $BoundingBox3d;
        expandTo(arg0: number, arg1: number, arg2: number): $BoundingBox3d;
        expandTo(arg0: $BoundingBox3dc): $BoundingBox3d;
        expandTo(arg0: $Vector3dc): $BoundingBox3d;
        intersect(arg0: $BoundingBox3dc): $BoundingBox3d;
        transformInverse(arg0: $Matrix4dc): $BoundingBox3d;
        transformInverse(arg0: $Pose3dc, arg1: $Matrix4d): $BoundingBox3d;
        transformInverse(arg0: $Pose3dc): $BoundingBox3d;
        setUnchecked(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): $BoundingBox3d;
        setUnchecked(arg0: $BoundingBox3dc): $BoundingBox3d;
        minX(): number;
        maxX(): number;
        minZ(): number;
        minY(): number;
        maxZ(): number;
        maxY(): number;
        size(arg0: $Vector3d): $Vector3d;
        size(): $Vector3d;
        length(): number;
        expand(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3d): $BoundingBox3d;
        expand(arg0: number, arg1: $BoundingBox3d): $BoundingBox3d;
        contains(arg0: $Vector3dc): boolean;
        contains(arg0: number, arg1: number, arg2: number): boolean;
        transform(arg0: $Pose3dc, arg1: $Matrix4d, arg2: $BoundingBox3d): $BoundingBox3d;
        transform(arg0: $Pose3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        transform(arg0: $Matrix4dc, arg1: $BoundingBox3d): $BoundingBox3d;
        move(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3d): $BoundingBox3d;
        width(): number;
        toMojang(): $AABB;
        volume(): number;
        expandTo(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3d): $BoundingBox3d;
        expandTo(arg0: $Vector3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        expandTo(arg0: $BoundingBox3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        intersects(arg0: $BoundingBox3dc): boolean;
        intersects(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        intersects(arg0: $AABB_): boolean;
        height(): number;
        chunkBoundsFrom(): $BoundingBox3i;
        chunkBoundsFrom(arg0: $BoundingBox3i): $BoundingBox3i;
        intersect(arg0: $BoundingBox3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        center(arg0: $Vector3d): $Vector3d;
        center(): $Vector3d;
        transformInverse(arg0: $Pose3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        transformInverse(arg0: $Pose3dc, arg1: $Matrix4d, arg2: $BoundingBox3d): $BoundingBox3d;
        transformInverse(arg0: $Matrix4dc, arg1: $BoundingBox3d): $BoundingBox3d;
        static CODEC: $Codec<$BoundingBox3d>;
        static EMPTY: $BoundingBox3d;
        constructor(arg0: $BlockPos_);
        constructor(arg0: $BoundingBox3ic);
        /**
         * @deprecated
         */
        constructor(arg0: $Vec3_, arg1: $Vec3_);
        constructor(arg0: $Position, arg1: $Position);
        constructor();
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number);
        constructor(arg0: $BoundingBox3dc);
        constructor(arg0: $AABB_);
        constructor(arg0: $BoundingBox);
    }
    export class $BoundingBox3i implements $BoundingBox3ic {
        expand(arg0: number, arg1: number, arg2: number): $BoundingBox3i;
        static from(arg0: $Iterable_<$BlockPos>): $BoundingBox3i;
        set(arg0: $BoundingBox3d): $BoundingBox3i;
        set(arg0: $BoundingBox3ic): $BoundingBox3i;
        set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): $BoundingBox3i;
        move(arg0: number, arg1: number, arg2: number): $BoundingBox3i;
        move(arg0: $Vector3ic): $BoundingBox3i;
        expandTo(arg0: $Vector3ic): $BoundingBox3i;
        expandTo(arg0: $BoundingBox3ic): $BoundingBox3i;
        expandTo(arg0: number, arg1: number, arg2: number): $BoundingBox3i;
        intersect(arg0: $BoundingBox3ic): $BoundingBox3i;
        setUnchecked(arg0: $BoundingBox3ic): $BoundingBox3i;
        setUnchecked(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): $BoundingBox3i;
        minX(): number;
        maxX(): number;
        minZ(): number;
        minY(): number;
        maxZ(): number;
        maxY(): number;
        size(arg0: $Vector3i): $Vector3i;
        length(): number;
        contains(arg0: number, arg1: number, arg2: number): boolean;
        contains(arg0: $Vector3ic): boolean;
        contains(arg0: $Vector3dc): boolean;
        move(arg0: $Vector3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        move(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3i): $BoundingBox3i;
        width(): number;
        toAABB(): $AABB;
        toMojang(): $BoundingBox;
        volume(): number;
        expandTo(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3i): $BoundingBox3i;
        expandTo(arg0: $BoundingBox3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        expandTo(arg0: $Vector3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        intersects(arg0: $BoundingBox3ic): boolean;
        intersects(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        intersects(arg0: $BoundingBox): boolean;
        height(): number;
        chunkBoundsFrom(arg0: $BoundingBox3i): $BoundingBox3i;
        chunkBoundsFrom(): $BoundingBox3i;
        intersect(arg0: $BoundingBox3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        center(arg0: $Vector3i): $Vector3i;
        static CODEC: $Codec<$BoundingBox3i>;
        static EMPTY: $BoundingBox3ic;
        constructor(arg0: $BoundingBox3d);
        constructor();
        constructor(arg0: $BoundingBox);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number);
        constructor(arg0: $BlockPos_, arg1: $BlockPos_);
        constructor(arg0: $BoundingBox3ic);
    }
    export class $Pose3dc {
    }
    export interface $Pose3dc {
        scale(): $Vector3dc;
        position(): $Vector3dc;
        transformNormalInverse(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformNormalInverse(arg0: $Vector3d): $Vector3d;
        transformNormalInverse(arg0: $Vec3_): $Vec3;
        withinTolerance(arg0: $Pose3d, arg1: number, arg2: number): boolean;
        bakeIntoMatrix(arg0: $Matrix4d): $Matrix4d;
        rotationPoint(): $Vector3dc;
        transformPositionInverse(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformPositionInverse(arg0: $Vec3_): $Vec3;
        transformPositionInverse(arg0: $Vector3d): $Vector3d;
        orientation(): $Quaterniondc;
        transformNormal(arg0: $Vec3_): $Vec3;
        transformNormal(arg0: $Vector3d): $Vector3d;
        transformNormal(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformPosition(arg0: $Vec3_): $Vec3;
        transformPosition(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformPosition(arg0: $Vector3d): $Vector3d;
        lerp(arg0: $Pose3dc, arg1: number, arg2: $Pose3d): $Pose3d;
    }
    export class $Pose3d implements $Pose3dc {
        scale(): $Vector3d;
        set(arg0: $Pose3dc): $Pose3d;
        rotationPoint(): $Vector3d;
        lerp(arg0: $Pose3dc, arg1: number): $Pose3d;
        transformNormalInverse(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformNormalInverse(arg0: $Vector3d): $Vector3d;
        transformNormalInverse(arg0: $Vec3_): $Vec3;
        withinTolerance(arg0: $Pose3d, arg1: number, arg2: number): boolean;
        bakeIntoMatrix(arg0: $Matrix4d): $Matrix4d;
        transformPositionInverse(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformPositionInverse(arg0: $Vec3_): $Vec3;
        transformPositionInverse(arg0: $Vector3d): $Vector3d;
        transformNormal(arg0: $Vec3_): $Vec3;
        transformNormal(arg0: $Vector3d): $Vector3d;
        transformNormal(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformPosition(arg0: $Vec3_): $Vec3;
        transformPosition(arg0: $Vector3dc, arg1: $Vector3d): $Vector3d;
        transformPosition(arg0: $Vector3d): $Vector3d;
        lerp(arg0: $Pose3dc, arg1: number, arg2: $Pose3d): $Pose3d;
        position(): $Vector3dc;
        orientation(): $Quaterniondc;
        static CODEC: $Codec<$Pose3d>;
        constructor(arg0: $Pose3dc);
        constructor();
        constructor(arg0: $Vector3d, arg1: $Quaterniond, arg2: $Vector3d, arg3: $Vector3d);
    }
    export class $BoundingBox3ic {
    }
    export interface $BoundingBox3ic {
        size(arg0: $Vector3i): $Vector3i;
        length(): number;
        contains(arg0: number, arg1: number, arg2: number): boolean;
        contains(arg0: $Vector3ic): boolean;
        contains(arg0: $Vector3dc): boolean;
        move(arg0: $Vector3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        move(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3i): $BoundingBox3i;
        width(): number;
        toAABB(): $AABB;
        toMojang(): $BoundingBox;
        volume(): number;
        expandTo(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3i): $BoundingBox3i;
        expandTo(arg0: $BoundingBox3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        expandTo(arg0: $Vector3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        intersects(arg0: $BoundingBox3ic): boolean;
        intersects(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        intersects(arg0: $BoundingBox): boolean;
        height(): number;
        chunkBoundsFrom(arg0: $BoundingBox3i): $BoundingBox3i;
        chunkBoundsFrom(): $BoundingBox3i;
        intersect(arg0: $BoundingBox3ic, arg1: $BoundingBox3i): $BoundingBox3i;
        center(arg0: $Vector3i): $Vector3i;
        minX(): number;
        maxX(): number;
        minZ(): number;
        minY(): number;
        maxZ(): number;
        maxY(): number;
    }
    export class $BoundingBox3dc {
    }
    export interface $BoundingBox3dc {
        size(arg0: $Vector3d): $Vector3d;
        size(): $Vector3d;
        length(): number;
        expand(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3d): $BoundingBox3d;
        expand(arg0: number, arg1: $BoundingBox3d): $BoundingBox3d;
        contains(arg0: $Vector3dc): boolean;
        contains(arg0: number, arg1: number, arg2: number): boolean;
        transform(arg0: $Pose3dc, arg1: $Matrix4d, arg2: $BoundingBox3d): $BoundingBox3d;
        transform(arg0: $Pose3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        transform(arg0: $Matrix4dc, arg1: $BoundingBox3d): $BoundingBox3d;
        move(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3d): $BoundingBox3d;
        width(): number;
        toMojang(): $AABB;
        volume(): number;
        expandTo(arg0: number, arg1: number, arg2: number, arg3: $BoundingBox3d): $BoundingBox3d;
        expandTo(arg0: $Vector3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        expandTo(arg0: $BoundingBox3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        intersects(arg0: $BoundingBox3dc): boolean;
        intersects(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        intersects(arg0: $AABB_): boolean;
        height(): number;
        chunkBoundsFrom(): $BoundingBox3i;
        chunkBoundsFrom(arg0: $BoundingBox3i): $BoundingBox3i;
        intersect(arg0: $BoundingBox3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        center(arg0: $Vector3d): $Vector3d;
        center(): $Vector3d;
        transformInverse(arg0: $Pose3dc, arg1: $BoundingBox3d): $BoundingBox3d;
        transformInverse(arg0: $Pose3dc, arg1: $Matrix4d, arg2: $BoundingBox3d): $BoundingBox3d;
        transformInverse(arg0: $Matrix4dc, arg1: $BoundingBox3d): $BoundingBox3d;
        minX(): number;
        maxX(): number;
        minZ(): number;
        minY(): number;
        maxZ(): number;
        maxY(): number;
    }
}
