RecipeViewerEvents.removeEntries('item', event => {
    const itemsToHide = [
    //^sophisticatedbackpacks:(?!upgrade_base|stack_upgrade_(starter_tier|tier_1|tier_2|tier_3|tier_4)).*upgrade.*/,
    //^create_sa:(?!brass_jetpack_chestplate$|netherite_jetpack_chestplate$|slime_helmet$|slime_boots$|small_filling_tank$|medium_filling_tank$|large_filling_tank$|small_fueling_tank$|medium_fueling_tank$|large_fueling_tank$).*/,
    'create_sa:flamethrower',
    /^createcasing:(.*creative|chorium_ingot)/,
    /^.*:.*incomplete.*/,
    /^.*:.*_spawn_egg$/,
    /^createframed:(.*_)?cardboard_window_pane$/,
	/^createframed:(.*_)?cardboard_window$/,
	/^createframed:(?:shiny_)?karpboard_block$/,
    'sophisticatedbackpacks:stack_upgrade_tier_4',
	'sophisticatedbackpacks:stack_downgrade_tier_1',
	'sophisticatedbackpacks:stack_downgrade_tier_2',
	'sophisticatedbackpacks:stack_downgrade_tier_3',
    'easy_villagers:auto_trader',
    'easy_villagers:farmer',
    'easy_villagers:breeder',
    'easy_villagers:converter',
    'easy_villagers:iron_farm',
    'easy_villagers:incubator',
    'easy_villagers:inventory_viewer',
    'ftblibrary:icon_item',
    'create:copper_backtank_placeable',
    'create:netherite_backtank_placeable',
    'create:incomplete_precision_mechanism',
    'create:unprocessed_obsidian_sheet',
    'minecraft:petrified_oak_slab',
    'minecraft:command_block',
    'minecraft:barrier',
    'minecraft:repeating_command_block',
    'minecraft:chain_command_block',
    'minecraft:structure_void',
    'minecraft:structure_block',
    'minecraft:jigsaw',
    'minecraft:filled_map',
    'minecraft:written_book',
    'minecraft:enchanted_book',
    'minecraft:command_block_minecart',
    'minecraft:knowledge_book',
    'minecraft:debug_stick',
    'createcasing:mldeg_shaft',
    'moonlight:spawn_box',
    'create:crushed_raw_osmium',
    'create:crushed_raw_platinum',
    'create:crushed_raw_silver',
    'create:crushed_raw_tin',
    'create:crushed_raw_lead',
    'create:crushed_raw_quicksilver',
    'create:crushed_raw_aluminum',
    'create:crushed_raw_uranium',
    'create:crushed_raw_nickel',
    // 'create:elevator_contact',
    'create:shopping_list',
    // 'create:schematic',
    'gravestone:obituary',
    'create:minecart_contraption',
    'create:furnace_minecart_contraption',
    'create:chest_minecart_contraption',
    'create:andesite_encased_shaft', 
    'create:brass_encased_shaft',
    'create:andesite_encased_cogwheel',
    'create:brass_encased_cogwheel',
    'create:andesite_encased_large_cogwheel',
    'create:brass_encased_large_cogwheel',
    'sophisticatedcore:xp_bucket',
    // 'create_pattern_schematics:pattern_schematic',
    'createcobblestone:mechanical_generator[block_entity_data={id:"createcobblestone:mechanical_generator",type:"createcobblestone:generator_types/limestone.json"}]', 
    'createcobblestone:mechanical_generator[block_entity_data={id:"createcobblestone:mechanical_generator",type:"createcobblestone:generator_types/basalt.json"}]', 
    'createcobblestone:mechanical_generator[block_entity_data={id:"createcobblestone:mechanical_generator",type:"createcobblestone:generator_types/scoria.json"}]', 
    'createcobblestone:mechanical_generator[block_entity_data={id:"createcobblestone:mechanical_generator",type:"createcobblestone:generator_types/stone.json"}]', 
    'createcobblestone:mechanical_generator[block_entity_data={id:"createcobblestone:mechanical_generator",type:"createcobblestone:generator_types/cobblestone.json"}]',
    'createcobblestone:mechanical_generator[block_entity_data={id:"createcobblestone:mechanical_generator",type:"none"}]'
    ]

    event.remove(itemsToHide)
})

RecipeViewerEvents.removeEntries('fluid', event => {
    event.remove('sophisticatedcore:xp_still')
})